import test from 'node:test';
import assert from 'node:assert/strict';
import {DodoEngine,DEMO_SCENARIO,validateProject,validateScenario,validateSequence} from '../lib/dodo/engine.ts';
import {SimulatedAdapter,PhysicalAdapter} from '../lib/dodo/adapter.ts';
import {JOINTS,STEP,neutralPose,validateJoints} from '../lib/dodo/config.ts';
import {defaultProject} from '../lib/dodo/library.ts';
import {dispatch} from '../lib/dodo/protocol.ts';
const steps=(e:DodoEngine,n:number)=>{for(let i=0;i<n;i++)e.step()};
test('All eight actuators respect displacement, velocity and acceleration under reversing commands',()=>{
 const a=new SimulatedAdapter();let seed=42;const rand=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
 for(let i=0;i<18000;i++){if(i%37===0)a.command(Object.fromEntries(JOINTS.map(j=>[j.id,j.min+rand()*(j.max-j.min)])) as ReturnType<typeof neutralPose>);
 const previous=structuredClone(a.state);a.advance(STEP);for(const j of JOINTS){const s=a.state[j.id],p=previous[j.id];assert.ok(s.position>=j.min-1e-9&&s.position<=j.max+1e-9);assert.ok(Math.abs(s.velocity)<=j.maxVelocity+1e-8);assert.ok(Math.abs(s.position-p.position)<=j.maxVelocity*STEP+1e-8);assert.ok(Math.abs(s.velocity-p.velocity)<=j.maxAcceleration*STEP+1e-8);}}
});
test('Tiny permitted speeds do not snap ahead of the velocity limit',()=>{const a=new SimulatedAdapter(JOINTS.map(j=>({...j,maxVelocity:.001,maxAcceleration:.001})));a.command({...neutralPose(),neck_yaw:.00009});let previous=0;for(let i=0;i<1000;i++){a.advance(STEP);const next=a.state.neck_yaw.position;assert.ok(Math.abs(next-previous)<=.001*STEP+1e-10);previous=next;}});
test('Manual commands retain priority and expose new targets while paused',()=>{const e=new DodoEngine();e.pause();e.setJoint('neck_yaw',12);assert.equal(e.snapshot().targets.neck_yaw,12);assert.equal(e.snapshot().pose.neck_yaw,0);e.pause();e.stimulus({presence:true,azimuth:-60,sound:1});steps(e,1800);assert.equal(e.mode,'manual');assert.ok(Math.abs(e.snapshot().pose.neck_yaw-12)<1e-8);});
test('Mode changes and reset never teleport the current pose',()=>{const e=new DodoEngine();e.setJoint('neck_yaw',25);steps(e,120);const p=e.snapshot().pose;e.setMode('auto');assert.deepEqual(e.snapshot().pose,p);e.reset();assert.deepEqual(e.snapshot().pose,p);steps(e,1800);assert.deepEqual(e.snapshot().pose,neutralPose());});
test('Pause freezes time, joints, breathing and blinking; stop holds until resumed',()=>{const e=new DodoEngine();steps(e,120);e.pause();const p=e.snapshot();steps(e,500);assert.deepEqual(e.snapshot(),p);e.resume();e.step();assert.ok(e.time>p.time);e.stop();const q=e.snapshot();steps(e,500);assert.deepEqual(e.snapshot(),q);assert.throws(()=>e.setJoint('neck_yaw',3));e.resume();e.step();assert.equal(e.status,'running');});
test('Presence, proximity, sound, light and contact produce appropriate states and log events',()=>{const e=new DodoEngine();e.stimulus({presence:true,distance:3,azimuth:30});e.step();assert.equal(e.state,'curiosidad');assert.ok(e.snapshot().targets.neck_yaw>0);e.stimulus({distance:1});e.step();assert.equal(e.state,'atención');e.stimulus({sound:.95});e.step();assert.equal(e.state,'sobresalto');e.stimulus({sound:0});steps(e,180);assert.equal(e.state,'recuperación');steps(e,480);e.stimulus({presence:false,light:.01});e.step();assert.equal(e.state,'reposo');assert.ok(e.snapshot().targets.head_pitch>5);e.touch();e.step();assert.equal(e.state,'sobresalto');assert.ok(e.logs.some(l=>l.message.includes('Contacto')));});
test('Two scenario replays produce identical frames after a smooth neutral preparation',()=>{const e=new DodoEngine();function replay(){e.playScenario(DEMO_SCENARIO);let guard=0;while(e.snapshot().playback?.kind==='preparing'&&guard++<10000)e.step();assert.ok(guard<10000);const states=[];for(let i=0;i<2640;i++){e.step();const s=e.snapshot();states.push({time:s.time,state:s.state,pose:s.pose,blink:s.blink,breath:s.breath,env:s.environment})}assert.equal(e.status,'paused');return states;}const a=replay();e.resume();e.setJoint('head_pitch',-14);steps(e,600);const b=replay();assert.deepEqual(a,b)});
test('Scenario replay protects its environment and seed from external edits',()=>{const e=new DodoEngine();e.playScenario(DEMO_SCENARIO);assert.throws(()=>e.setSeed(999));assert.throws(()=>e.stimulus({light:.1}));assert.throws(()=>e.touch());e.setMode('manual');assert.equal(e.snapshot().playback,null);e.setSeed(999);});
test('Sequences visit each saved pose in order before completing',()=>{const e=new DodoEngine();const p=defaultProject();e.playSequence(p.sequences[0]);const visited=new Set<number>();for(let i=0;i<10000&&e.snapshot().playback;i++){e.step();visited.add(e.snapshot().playback?.progress??1)}assert.equal(e.snapshot().playback,null);assert.ok(visited.has(1/3)&&visited.has(2/3));assert.deepEqual(e.snapshot().pose,neutralPose());});
test('Configuration and library export/import round-trip without altering pose or sequence data',()=>{const p=defaultProject();p.poses.push({id:'test-pose',name:'Prueba',pose:{...neutralPose(),head_yaw:18}});p.scenarios.push({...DEMO_SCENARIO,id:'test-scenario',name:'Prueba de escenario'});assert.deepEqual(validateProject(JSON.parse(JSON.stringify(p))),p);});
test('Malformed projects, duplicate IDs, non-finite values and invalid limits are rejected atomically',()=>{const p=defaultProject();assert.throws(()=>validateProject({...p,version:'2.0'}));assert.throws(()=>validateProject({...p,poses:[p.poses[0],p.poses[0]]}));assert.throws(()=>validateProject({...p,seed:NaN}));assert.throws(()=>validateJoints(JOINTS.map(j=>({...j,maxVelocity:Infinity}))));assert.throws(()=>validateSequence({id:'bad',name:'bad',frames:[{pose:{...neutralPose(),head_yaw:Infinity},name:'a',hold:1}]}));assert.throws(()=>validateScenario({...DEMO_SCENARIO,events:[{at:23,touch:true}]}));const e=new DodoEngine();const before=e.snapshot();assert.throws(()=>e.setJoint('neck_yaw',100));assert.deepEqual(e.snapshot(),before);assert.throws(()=>e.stimulus({light:2}));});
test('Protocol rejects unknown versions/units and never fabricates physical telemetry',()=>{const e=new DodoEngine();assert.throws(()=>dispatch(e,{version:'2',type:'stop'}));assert.throws(()=>dispatch(e,{version:'1.0',type:'set_pose',unit:'rad',positions:neutralPose()}));dispatch(e,{version:'1.0',type:'set_pose',unit:'deg',positions:{...neutralPose(),head_yaw:15}});steps(e,120);const t=e.telemetry();assert.equal(t.measured,null);assert.equal(t.connected,false);assert.equal(t.source,'simulation');assert.throws(()=>new PhysicalAdapter().connect());dispatch(e,{version:'1.0',type:'stop'});assert.equal(e.status,'stopped');});
test('Manual control during reset cancels reset and cannot cause a later teleport',()=>{const e=new DodoEngine();e.setJoint('neck_yaw',25);steps(e,400);e.reset();e.setJoint('neck_yaw',10);let prev=e.snapshot().pose.neck_yaw;for(let i=0;i<2000;i++){e.step();const p=e.snapshot().pose.neck_yaw;assert.ok(Math.abs(p-prev)<=30*STEP+1e-8);prev=p;}assert.ok(Math.abs(prev-10)<1e-8);});
