import {useRef,useState} from 'react';
import {Play,Plus,Save,Trash2,Download,Upload,ChevronDown,BookOpen,Activity,Hand,Volume2,UserRound,Sun,ArrowDown,ArrowUp} from 'lucide-react';
import {toast} from 'sonner';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {DodoEngine,validName,validateSequence,validateScenario,validateProject,type Snapshot,type Project,type Sequence,type Scenario} from '@/lib/dodo/engine';
import {JOINTS,type JointConfig} from '@/lib/dodo/config';
import type {Environment} from '@/lib/dodo/behavior';
export type Act=(fn:()=>void)=>void;
export function Choice({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Range({label,value,min,max,step=1,unit='',onChange,disabled=false}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(v:number)=>void;disabled?:boolean}){return <div className="range-control"><div><label>{label}</label><output>{step<1?value.toFixed(2):value.toFixed(0)}{unit}</output></div><Slider ref={el=>{el?.querySelectorAll('[role="slider"]').forEach(node=>node.setAttribute('aria-label',label));}} aria-label={label} min={min} max={max} step={step} value={[value]} onValueChange={v=>onChange(v[0])} disabled={disabled}/></div>}
export function EnvironmentPanel({engine,snap,act}:{engine:DodoEngine;snap:Snapshot;act:Act}){
 const locked=!!snap.playback&&snap.playback.kind!=='sequence';const env=snap.environment;
 const stimulus=(patch:Partial<Environment>)=>act(()=>engine.stimulus(patch));
 return <><p className="panel-note">Estímulos virtuales. El modo autónomo decide la respuesta; en manual mantienes el control.</p>{locked&&<p className="inline-warning">Escenario en curso. Cambia de modo para finalizarlo.</p>}
 <div className="presence-row"><div><UserRound size={18}/><span>Hay alguien cerca</span></div><Switch aria-label="Presencia simulada" checked={env.presence} disabled={locked} onCheckedChange={v=>stimulus({presence:v})}/></div>
 <Range label="Distancia de la persona" value={env.distance} min={.1} max={5} step={.1} unit=" m" onChange={v=>stimulus({distance:v})} disabled={locked}/>
 <Range label="Dirección de la persona" value={env.azimuth} min={-60} max={60} step={1} unit="°" onChange={v=>stimulus({azimuth:v})} disabled={locked}/>
 <Range label="Nivel de sonido" value={env.sound*100} min={0} max={100} unit=" %" onChange={v=>stimulus({sound:v/100})} disabled={locked}/>
 <Range label="Luz ambiente" value={env.light*100} min={0} max={100} unit=" %" onChange={v=>stimulus({light:v/100})} disabled={locked}/>
 <button className="outline wide" disabled={locked} onClick={()=>act(()=>engine.touch())}><Hand size={16}/> Simular contacto</button>
 <div className="explanation"><strong>{snap.state[0].toUpperCase()+snap.state.slice(1)}</strong><p>{snap.mode==='manual'?'El comportamiento se observa, pero no envía órdenes a las articulaciones.':snap.state==='sobresalto'?'Un contacto, un sonido fuerte o una aproximación muy cercana activa esta respuesta.':snap.state==='recuperación'?'El dodo regresa gradualmente a un estado de calma.':env.light<.12?'Con poca luz adopta una postura de descanso.':env.presence?'La cabeza sigue la dirección de la persona simulada.':'Pequeñas variaciones, respiración y pausas mantienen el movimiento natural.'}</p></div></>;
}
const uid=()=>crypto.randomUUID();
export function LibraryPanel({engine,snap,project,update,act}:{engine:DodoEngine;snap:Snapshot;project:Project;update:(fn:(p:Project)=>Project)=>void;act:Act}){
 const [poseName,setPoseName]=useState('Mi postura');const [sequence,setSequence]=useState<Sequence>({id:'draft',name:'Mi secuencia',frames:[]});const [scenario,setScenario]=useState<Scenario>(()=>structuredClone(project.scenarios[0]||{id:'draft',name:'Mi escenario',seed:42,duration:20,events:[]}));
 const [at,setAt]=useState(2);const [sequenceChoice,setSequenceChoice]=useState('');
 const savePose=()=>act(()=>{if(project.poses.length>=100)throw new Error('La biblioteca admite 100 posturas. Exporta o elimina alguna antes de añadir más.');const name=validName(poseName);update(p=>({...p,poses:[...p.poses,{id:uid(),name,pose:{...snap.pose}}]}));toast.success('Postura guardada en este navegador');});
 const deleteItem=(kind:'poses'|'sequences'|'scenarios',id:string)=>{const removed=project[kind].find(x=>x.id===id);const index=project[kind].findIndex(x=>x.id===id);update(p=>({...p,[kind]:p[kind].filter(x=>x.id!==id)}));toast('Elemento eliminado',{action:{label:'Deshacer',onClick:()=>update(p=>{if(!removed||p[kind].some(x=>x.id===id))return p;const restored=[...p[kind]];restored.splice(Math.min(index,restored.length),0,removed);return {...p,[kind]:restored};})}})};
 const moveFrame=(i:number,d:number)=>{setSequence(s=>{const frames=[...s.frames];[frames[i],frames[i+d]]=[frames[i+d],frames[i]];return {...s,frames}})};
 const saveSequence=()=>act(()=>{if(project.sequences.length>=100&&!project.sequences.some(s=>s.id===sequence.id))throw new Error('La biblioteca admite 100 secuencias.');const valid=validateSequence({...sequence,id:sequence.id==='draft'?uid():sequence.id},project.joints);update(p=>({...p,sequences:[...p.sequences.filter(s=>s.id!==valid.id),valid]}));setSequence(valid);toast.success('Secuencia guardada');});
 const saveScenario=()=>act(()=>{if(project.scenarios.length>=100&&!project.scenarios.some(s=>s.id===scenario.id))throw new Error('La biblioteca admite 100 escenarios.');const valid=validateScenario({...scenario,id:scenario.id==='draft'?uid():scenario.id});update(p=>({...p,scenarios:[...p.scenarios.filter(s=>s.id!==valid.id),valid]}));setScenario(valid);toast.success('Escenario guardado');});
 return <><p className="panel-note">Biblioteca local de este navegador. Exporta el proyecto para conservar una copia o llevarlo a otro equipo.</p><Tabs defaultValue="poses"><TabsList variant="line" className="library-tabs"><TabsTrigger value="poses">Posturas</TabsTrigger><TabsTrigger value="sequences">Secuencias</TabsTrigger><TabsTrigger value="scenarios">Escenarios</TabsTrigger></TabsList>
 <TabsContent value="poses"><div className="field"><label htmlFor="pose-name">Nombre de la postura</label><input id="pose-name" maxLength={80} value={poseName} onChange={e=>setPoseName(e.target.value)}/></div><button className="primary wide" onClick={savePose}><Save size={15}/> Guardar posición actual</button><div className="library-list">{project.poses.map(p=><div className="library-item" key={p.id}><div><strong>{p.name}</strong><small>8 articulaciones · grados</small></div><button className="icon-button" aria-label={`Aplicar ${p.name}`} onClick={()=>act(()=>engine.setPose(p.pose))}><Play size={15}/></button><button className="icon-button subtle" aria-label={`Eliminar postura ${p.name}`} onClick={()=>deleteItem('poses',p.id)}><Trash2 size={14}/></button></div>)}</div></TabsContent>
 <TabsContent value="sequences"><div className="saved-list">{project.sequences.map(s=><div key={s.id} className="library-item"><button className="text-action" onClick={()=>setSequence(structuredClone(s))}><strong>{s.name}</strong><small>{s.frames.length} pasos · editar</small></button><button className="icon-button" aria-label={`Reproducir ${s.name}`} onClick={()=>act(()=>engine.playSequence(s))}><Play size={15}/></button><button className="icon-button subtle" aria-label={`Eliminar secuencia ${s.name}`} onClick={()=>deleteItem('sequences',s.id)}><Trash2 size={14}/></button></div>)}</div>
 <div className="section-line"><strong>Editor de secuencia</strong><button onClick={()=>setSequence({id:'draft',name:'Mi secuencia',frames:[]})}>Nueva</button></div><div className="field"><label htmlFor="sequence-name">Nombre de la secuencia</label><input id="sequence-name" value={sequence.name} maxLength={80} onChange={e=>setSequence(s=>({...s,name:e.target.value}))}/></div>
 <p className="microcopy">Cada paso llega a su postura respetando los límites y después espera el tiempo indicado.</p>
 {sequence.frames.map((f,i)=><div className="frame-item" key={i}><div><span className="step-number">{i+1}</span><strong>{f.name}</strong><button className="tiny" disabled={i===0} aria-label={`Subir paso ${i+1}`} onClick={()=>moveFrame(i,-1)}><ArrowUp size={13}/></button><button className="tiny" disabled={i===sequence.frames.length-1} aria-label={`Bajar paso ${i+1}`} onClick={()=>moveFrame(i,1)}><ArrowDown size={13}/></button><button className="tiny" aria-label={`Eliminar paso ${i+1}`} onClick={()=>setSequence(s=>({...s,frames:s.frames.filter((_,index)=>index!==i)}))}><Trash2 size={13}/></button></div><label>Espera <input aria-label={`Espera paso ${i+1}`} type="number" min={0} max={30} step={.1} value={f.hold} onChange={e=>setSequence(s=>({...s,frames:s.frames.map((f,index)=>index===i?{...f,hold:Number(e.target.value)}:f)}))}/> s</label></div>)}
 <button className="outline wide" disabled={sequence.frames.length>=40} onClick={()=>setSequence(s=>({...s,frames:[...s.frames,{name:`Captura ${s.frames.length+1}`,pose:{...snap.pose},hold:1}]}))}><Plus size={15}/> Añadir posición actual</button>
 {project.poses.length>0&&<><Choice label="Postura para añadir a secuencia" value={sequenceChoice} options={project.poses.map(p=>({value:p.id,label:p.name}))} onChange={setSequenceChoice}/><button className="outline wide" disabled={!sequenceChoice||sequence.frames.length>=40} onClick={()=>{const p=project.poses.find(p=>p.id===sequenceChoice);if(p)setSequence(s=>({...s,frames:[...s.frames,{name:p.name,pose:{...p.pose},hold:1}]}))}}>Añadir postura guardada</button></>}
 <div className="button-pair"><button className="primary" disabled={!sequence.frames.length} onClick={saveSequence}><Save size={14}/> Guardar</button><button className="outline" disabled={!sequence.frames.length} onClick={()=>act(()=>engine.playSequence(sequence))}><Play size={14}/> Probar</button></div></TabsContent>
 <TabsContent value="scenarios"><div className="saved-list">{project.scenarios.map(s=><div className="library-item" key={s.id}><button className="text-action" onClick={()=>setScenario(structuredClone(s))}><strong>{s.name}</strong><small>{s.duration} s · semilla {s.seed}</small></button><button className="icon-button" aria-label={`Reproducir escenario ${s.name}`} onClick={()=>act(()=>engine.playScenario(s))}><Play size={15}/></button><button className="icon-button subtle" aria-label={`Eliminar escenario ${s.name}`} onClick={()=>deleteItem('scenarios',s.id)}><Trash2 size={14}/></button></div>)}</div>
 <div className="section-line"><strong>Editor de escenario</strong><button onClick={()=>setScenario({id:'draft',name:'Mi escenario',seed:snap.seed,duration:20,events:[]})}>Nuevo</button></div><div className="field"><label htmlFor="scenario-name">Nombre del escenario</label><input id="scenario-name" value={scenario.name} maxLength={80} onChange={e=>setScenario(s=>({...s,name:e.target.value}))}/></div><div className="two-fields"><label>Duración (s)<input type="number" aria-label="Duración del escenario" min={1} max={600} value={scenario.duration} onChange={e=>setScenario(s=>({...s,duration:Number(e.target.value)}))}/></label><label>Semilla<input type="number" aria-label="Semilla del escenario" min={0} max={4294967295} value={scenario.seed} onChange={e=>setScenario(s=>({...s,seed:Number(e.target.value)}))}/></label></div>
 <p className="microcopy">Configura los estímulos en Entorno y captura su estado en el segundo elegido. La reproducción comienza desde neutro.</p>
 {scenario.events.map((e,i)=><div className="event-item" key={i}><input aria-label={`Segundo del evento ${i+1}`} type="number" min={0} max={scenario.duration} step={.1} value={e.at} onChange={event=>setScenario(s=>({...s,events:s.events.map((v,k)=>k===i?{...v,at:Number(event.target.value)}:v)}))}/><span>{e.touch?'Contacto':Object.entries(e.env||{}).map(([k,v])=>`${({presence:'Presencia',distance:'m',azimuth:'°',sound:'Sonido',light:'Luz'} as Record<string,string>)[k]} ${v===true?'sí':v===false?'no':v}`).join(' · ')}</span><button className="tiny" aria-label={`Eliminar evento ${i+1}`} onClick={()=>setScenario(s=>({...s,events:s.events.filter((_,k)=>k!==i)}))}><Trash2 size={14}/></button></div>)}
 <div className="field"><label htmlFor="event-time">Añadir en el segundo</label><input id="event-time" type="number" min={0} max={scenario.duration} step={.1} value={at} onChange={e=>setAt(Number(e.target.value))}/></div><button className="outline wide" onClick={()=>setScenario(s=>({...s,events:[...s.events,{at,env:{...snap.environment}}]}))}><Plus size={14}/> Capturar entorno actual</button><button className="outline wide" onClick={()=>setScenario(s=>({...s,events:[...s.events,{at,touch:true}]}))}><Hand size={14}/> Añadir contacto</button><div className="button-pair"><button className="primary" onClick={saveScenario}><Save size={14}/> Guardar</button><button className="outline" onClick={()=>act(()=>engine.playScenario(scenario))}><Play size={14}/> Probar</button></div></TabsContent>
 </Tabs></>;
}
export function downloadJson(value:unknown,filename:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ProjectPanel({engine,project,update,act,onImport,onDetails}:{engine:DodoEngine;project:Project;update:(fn:(p:Project)=>Project)=>void;act:Act;onImport:(p:Project)=>void;onDetails:(view:'reference'|'hardware')=>void}){
 const [draft,setDraft]=useState<JointConfig[]>(()=>structuredClone(project.joints));const [seed,setSeed]=useState(project.seed);const file=useRef<HTMLInputElement>(null);
 return <><div className="project-spec"><span>ESCALA DE REFERENCIA</span><strong>700 <small>mm</small></strong><p>Reconstrucción provisional · base fija</p></div><button className="outline wide" onClick={()=>onDetails('reference')}><BookOpen size={15}/> Anatomía y fuentes</button><button className="outline wide" onClick={()=>onDetails('hardware')}><Activity size={15}/> Hardware y telemetría</button>
 <div className="section-line"><strong>Proyecto portátil</strong></div><button className="primary wide" onClick={()=>downloadJson({...project,seed:engine.seed,joints:engine.adapter.joints},'dodo-twin-proyecto.json')}><Download size={15}/> Exportar proyecto</button><button className="outline wide" onClick={()=>file.current?.click()}><Upload size={15}/> Importar proyecto</button><input ref={file} type="file" accept=".json,application/json" className="sr-only" aria-label="Archivo de proyecto" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>2000000){toast.error('El archivo supera 2 MB.');return;}try{const p=validateProject(JSON.parse(await f.text()));onImport(p);setDraft(structuredClone(p.joints));setSeed(p.seed);toast.success('Proyecto importado · simulación reiniciada');}catch(err){toast.error(err instanceof Error?err.message:'Archivo inválido')}}}/>
 <p className="microcopy">Incluye articulaciones, posturas, secuencias, escenarios y semilla. La importación sustituye la biblioteca local y reinicia la simulación.</p>
 <div className="field"><label htmlFor="project-seed">Semilla de comportamiento</label><input id="project-seed" type="number" min={0} max={4294967295} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></div><button className="outline wide" onClick={()=>act(()=>{engine.setSeed(seed);update(p=>({...p,seed}));toast.success('Semilla aplicada');})}>Aplicar semilla</button>
 <div className="section-line"><strong>Límites de articulaciones</strong></div><p className="microcopy">Valores provisionales. Vuelve a neutro y activa Parada antes de aplicar. Puedes reducir la envolvente, no ampliarla.</p>
 {draft.map((j,index)=><details className="joint-config" key={j.id}><summary>{j.label}<ChevronDown size={14}/></summary><p>{j.mechanism}</p><div className="two-fields">{(['min','max','neutral','maxVelocity','maxAcceleration'] as const).map(k=><label key={k}>{({min:'Mínimo (°)',max:'Máximo (°)',neutral:'Neutro (°)',maxVelocity:'Velocidad (°/s)',maxAcceleration:'Aceleración (°/s²)'})[k]}<input aria-label={`${j.label} ${k}`} type="number" step={.1} value={j[k]} onChange={e=>setDraft(d=>d.map((v,i)=>i===index?{...v,[k]:Number(e.target.value)}:v))}/></label>)}</div><span className="microcopy">Eje {j.axis.toUpperCase()} · Padre {j.parent}</span></details>)}
 <button className="primary wide" onClick={()=>act(()=>{validateProject({...project,joints:draft});engine.configure(draft);update(p=>({...p,joints:structuredClone(engine.adapter.joints)}));toast.success('Límites aplicados');})}>Aplicar límites</button></>;
}
