import { JOINTS, STEP, PROTOCOL_VERSION, neutralPose, validatePose, validateJoints, type Pose, type JointId, type JointConfig } from './config.ts';
import {SimulatedAdapter} from './adapter.ts';
import {DEFAULT_ENV,behaviorAt,validateEnvironment,type Environment,type BehaviorState} from './behavior.ts';
export interface LogEvent {id:number;t:number;kind:'estado'|'estímulo'|'control'|'sistema';message:string;}
export interface SavedPose {id:string;name:string;pose:Pose;}
export interface Sequence {id:string;name:string;frames:{name:string;pose:Pose;hold:number}[];}
export interface Scenario {id:string;name:string;seed:number;duration:number;events:{at:number;env?:Partial<Environment>;touch?:boolean}[];}
export const DEMO_SCENARIO:Scenario={id:'encuentro',name:'Un encuentro · 22 s',seed:42,duration:22,events:[{at:1,env:{presence:true,distance:3,azimuth:-35}},{at:5,env:{distance:1,azimuth:15}},{at:9,env:{sound:.95}},{at:9.4,env:{sound:0}},{at:14,env:{azimuth:35}},{at:17,touch:true},{at:20,env:{presence:false,light:.08}}]};
export interface Snapshot {time:number;mode:'auto'|'manual';status:'running'|'paused'|'stopped';state:BehaviorState;pose:Pose;targets:Pose;environment:Environment;blink:number;breath:number;seed:number;playback:null|{kind:'sequence'|'scenario'|'preparing';name:string;progress:number};logs:LogEvent[];}
export class DodoEngine {
 adapter:SimulatedAdapter; environment:Environment={...DEFAULT_ENV};time=0;seed=42;mode:'auto'|'manual'='auto';status:'running'|'paused'|'stopped'='running';state:BehaviorState='reposo';blink=0;breath=.5;logs:LogEvent[]=[];
 private resetting=false;private logId=0;private ticks=0;private manual:Pose;private startleUntil=0;private recoveryUntil=0;
 private sequence:{data:Sequence;index:number;held:number}|null=null;
 private scenario:{data:Scenario;index:number;preparing:boolean}|null=null;
 constructor(joints=JOINTS){this.adapter=new SimulatedAdapter(joints);this.manual=neutralPose(joints);this.log('sistema','Simulación lista · hardware pendiente de conexión');}
 log(kind:LogEvent['kind'],message:string){this.logs=[{id:++this.logId,t:this.time,kind,message},...this.logs].slice(0,150);}
 cancelPlayback(){this.sequence=null;this.scenario=null;this.resetting=false;}
 setMode(mode:'auto'|'manual'){if(mode!=='auto'&&mode!=='manual')throw new Error('Modo inválido.');if(mode===this.mode&&!this.sequence&&!this.scenario&&!this.resetting)return;this.cancelPlayback();this.manual=this.adapter.pose();this.mode=mode;if(mode==='manual')this.adapter.command(this.manual);this.log('control',mode==='auto'?'Comportamiento autónomo activado':'Control manual · comportamiento sin prioridad');}
 setPose(pose:Pose){const value=validatePose(pose,this.adapter.joints);if(this.status==='stopped')throw new Error('Reanuda la simulación antes de mover el dodo.');this.setMode('manual');this.manual=value;this.adapter.command(value);this.log('control','Nueva postura solicitada');}
 setJoint(id:JointId,value:number){const pose={...(this.mode==='manual'?this.manual:this.adapter.pose()),[id]:value};this.setPose(pose);}
 stimulus(patch:Partial<Environment>,fromScenario=false){const valid=validateEnvironment(patch);if(this.scenario&&!fromScenario)throw new Error('Finaliza el escenario antes de editar el entorno.');const prev=this.environment;this.environment={...prev,...valid};
  if((this.environment.sound>.8&&prev.sound<=.8)||(this.environment.presence&&this.environment.distance<.35&&(!prev.presence||prev.distance>=.35)))this.startle();
  const labels:Record<string,string>={presence:'Presencia',distance:'Distancia',azimuth:'Dirección',sound:'Sonido',light:'Luz'};
  this.log('estímulo',Object.entries(valid).map(([k,v])=>`${labels[k]}: ${typeof v==='boolean'?(v?'sí':'no'):Number(v).toFixed(2)}`).join(' · '));
 }
 touch(fromScenario=false){if(this.scenario&&!fromScenario)throw new Error('Finaliza el escenario antes de aplicar contacto.');this.startle();this.log('estímulo','Contacto simulado en el cuerpo');}
 private startle(){this.startleUntil=this.time+1.25;this.recoveryUntil=this.time+4.5;}
 pause(){if(this.status==='stopped')return;this.status=this.status==='paused'?'running':'paused';this.log('control',this.status==='paused'?'Simulación en pausa':'Simulación reanudada');}
 stop(){this.cancelPlayback();this.status='stopped';this.adapter.hold();this.manual=this.adapter.pose();this.log('control','Parada virtual · posición retenida');}
 resume(){this.status='running';this.log('control','Simulación reanudada');}
 reset(){this.cancelPlayback();this.mode='manual';this.status='running';this.environment={...DEFAULT_ENV};this.startleUntil=0;this.recoveryUntil=0;this.manual=neutralPose(this.adapter.joints);this.adapter.command(this.manual);this.resetting=true;this.log('control','Reinicio · regreso suave a postura neutra');}
 setSeed(seed:number){if(this.scenario)throw new Error('Finaliza el escenario antes de cambiar la semilla.');if(!Number.isSafeInteger(seed)||seed<0||seed>4294967295)throw new Error('La semilla debe ser un entero entre 0 y 4294967295.');this.seed=seed;this.log('sistema',`Semilla reproducible: ${seed}`);}
 configure(joints:unknown){const next=validateJoints(joints);if(this.status!=='stopped')throw new Error('Detén la simulación para editar límites.');for(const j of next)if(this.adapter.state[j.id].position<j.min||this.adapter.state[j.id].position>j.max)throw new Error('La posición actual queda fuera de los nuevos límites. Vuelve a neutro primero.');this.adapter.joints=next;this.manual=this.adapter.pose();this.log('sistema','Configuración de articulaciones actualizada');}
 playSequence(data:Sequence){const seq=validateSequence(data,this.adapter.joints);this.cancelPlayback();this.status='running';this.mode='manual';this.sequence={data:seq,index:0,held:0};this.manual=seq.frames[0].pose;this.log('control',`Secuencia: ${seq.name}`);}
 playScenario(data:Scenario){const scenario=validateScenario(data);this.cancelPlayback();this.status='running';this.mode='manual';this.manual=neutralPose(this.adapter.joints);this.scenario={data:scenario,index:0,preparing:true};this.log('control',`Preparando escenario: ${scenario.name}`);}
 step(){if(this.status!=='running')return;const dt=STEP;
  if(this.resetting){this.adapter.command(this.manual);this.adapter.advance(dt);if(this.adapter.settled()){this.resetting=false;this.adapter.reset();this.ticks=0;this.time=0;this.state='reposo';this.blink=0;this.breath=.5;this.logs=[];this.log('sistema','Simulación reiniciada en postura neutra');}return;}
  if(this.scenario?.preparing){this.adapter.command(this.manual);this.adapter.advance(dt);if(this.adapter.settled()){this.adapter.reset();this.ticks=0;this.time=0;this.environment={...DEFAULT_ENV};this.seed=this.scenario.data.seed;this.startleUntil=0;this.recoveryUntil=0;this.mode='auto';this.scenario.preparing=false;const initial=behaviorAt(0,this.seed,this.environment,0,0,this.adapter.joints);this.state=initial.state;this.blink=initial.blink;this.breath=initial.breath;this.log('control',`Escenario iniciado · semilla ${this.seed}`);}return;}
  this.time=++this.ticks*dt;
  if(this.scenario){const s=this.scenario;while(s.index<s.data.events.length&&s.data.events[s.index].at<=this.time){const e=s.data.events[s.index++];if(e.env)this.stimulus(e.env,true);if(e.touch)this.touch(true);}}
  const b=behaviorAt(this.time,this.seed,this.environment,this.startleUntil,this.recoveryUntil,this.adapter.joints);
  if(b.state!==this.state){this.state=b.state;this.log('estado',`${b.state[0].toUpperCase()+b.state.slice(1)}${this.mode==='manual'?' · sin control de articulaciones':''}`);}
  this.blink=b.blink;this.breath=b.breath;
  this.adapter.command(this.mode==='auto'?b.pose:this.manual);this.adapter.advance(dt);
  if(this.sequence&&this.adapter.settled()){const s=this.sequence;s.held+=dt;if(s.held>=s.data.frames[s.index].hold){s.index++;s.held=0;if(s.index>=s.data.frames.length){this.log('control',`Secuencia completada: ${s.data.name}`);this.sequence=null;}else this.manual={...s.data.frames[s.index].pose};}}
  if(this.scenario&&this.time>=this.scenario.data.duration){this.log('control',`Escenario completado: ${this.scenario.data.name}`);this.scenario=null;this.status='paused';}
 }
 snapshot():Snapshot {const s=this.scenario,q=this.sequence;return {time:this.time,mode:this.mode,status:this.status,state:this.state,pose:this.adapter.pose(),targets:this.adapter.targets(),environment:{...this.environment},blink:this.blink,breath:this.breath,seed:this.seed,logs:this.logs,playback:this.resetting?{kind:'preparing',name:'Reinicio',progress:0}:s?{kind:s.preparing?'preparing':'scenario',name:s.data.name,progress:s.preparing?0:this.time/s.data.duration}:q?{kind:'sequence',name:q.data.name,progress:q.index/q.data.frames.length}:null};}
 telemetry(){return this.adapter.telemetry(this.time)}
}
export function validId(value:unknown){if(typeof value!=='string'||!value.trim()||value.length>100)throw new Error('Identificador inválido.');return value;}
export function uniqueIds(items:{id:string}[]){const seen=new Set<string>();for(const item of items){validId(item.id);if(seen.has(item.id))throw new Error('Identificadores duplicados.');seen.add(item.id);}}
export function validName(value:unknown){if(typeof value!=='string'||!value.trim()||value.length>80)throw new Error('El nombre debe tener entre 1 y 80 caracteres.');return value.trim();}
export function validateSequence(input:unknown,joints=JOINTS):Sequence {const s=input as Sequence;if(!s||typeof s.id!=='string'||!Array.isArray(s.frames)||s.frames.length<1||s.frames.length>40)throw new Error('Secuencia inválida (1–40 pasos).');return {id:validId(s.id),name:validName(s.name),frames:s.frames.map(f=>{if(!f||!Number.isFinite(f.hold)||f.hold<0||f.hold>30)throw new Error('Espera inválida (0–30 s).');return {name:validName(f.name),pose:validatePose(f.pose,joints),hold:f.hold};})};}
export function validateScenario(input:unknown):Scenario {const s=input as Scenario;if(!s||typeof s.id!=='string'||!Array.isArray(s.events)||s.events.length>200||!Number.isSafeInteger(s.seed)||s.seed<0||s.seed>4294967295||!Number.isFinite(s.duration)||s.duration<1||s.duration>600)throw new Error('Escenario inválido.');return {id:validId(s.id),name:validName(s.name),seed:s.seed,duration:s.duration,events:s.events.map(e=>{if(!e||!Number.isFinite(e.at)||e.at<0||e.at>s.duration||(!e.env&&e.touch!==true)||e.touch!==undefined&&typeof e.touch!=='boolean')throw new Error('Evento de escenario inválido.');return {at:e.at,...(e.env?{env:validateEnvironment(e.env)}:{}),...(e.touch?{touch:true}:{})};}).sort((a,b)=>a.at-b.at)};}
export interface Project {version:string;scale_m:number;seed:number;joints:JointConfig[];poses:SavedPose[];sequences:Sequence[];scenarios:Scenario[];}
export function validateProject(input:unknown):Project {const p=input as Project;if(!p||p.version!==PROTOCOL_VERSION||p.scale_m!==.7||!Number.isSafeInteger(p.seed)||p.seed<0||p.seed>4294967295)throw new Error('Archivo incompatible con Dodo Twin 1.0.');const joints=validateJoints(p.joints);if(!Array.isArray(p.poses)||p.poses.length>100||!Array.isArray(p.sequences)||p.sequences.length>100||!Array.isArray(p.scenarios)||p.scenarios.length>100)throw new Error('Biblioteca inválida.');uniqueIds(p.poses);uniqueIds(p.sequences);uniqueIds(p.scenarios);return {version:PROTOCOL_VERSION,scale_m:.7,seed:p.seed,joints,poses:p.poses.map(v=>{if(typeof v.id!=='string')throw new Error('Postura sin identificador.');return{id:v.id,name:validName(v.name),pose:validatePose(v.pose,joints)}}),sequences:p.sequences.map(s=>validateSequence(s,joints)),scenarios:p.scenarios.map(validateScenario)};}
